### ISSUE TITLE
Rename `components` directory to `src/`

### ISSUE THREAD

**Issue by sadafie** [meetup/meetup-web-components#10]
The word `components` is overused, and in parent applications we end up with imports like `mup-web-components/components/...`. @mmcgahan and I talked a bit about this, and if there're no objections, we'd like to rename `components/` to `src/`.

**Comment by mmcgahan** [comment]
I think actually this change will work well with [WC-2](https://meetup.atlassian.net/browse/WC-2), which will require moving all pre-transpiled files into a `src/` directory. Since the icon files don't need to be transpiled, it's fine for them to not be in `src/`
