### ISSUE TITLE
Unmet peer dependency warning

### ISSUE THREAD

**Issue by sadafie** [meetup/meetup-web-components#14]
```
$ npm i 
meetup-web-components@0.1.0 /Users/sadaf/git_repo/meetup-web-components
├── UNMET PEER DEPENDENCY bourbon@4.2.7
├── coveralls@2.11.14
├─┬ eslint@3.9.1
│ └─┬ inquirer@0.12.0
│   ├─┬ readline2@1.0.1
│   │ └── mute-stream@0.0.5
│   ├── run-async@0.1.0
│   └── rx-lite@3.1.2
└─┬ meetup-web-platform@0.5.189
  └─┬ eslint@3.6.1
    └─┬ inquirer@0.12.0
      └── run-async@0.1.0

npm WARN sassquatch2@2.4.2 requires a peer of bourbon@4.2.3 but none was installed.
```

The latest version of sassquatch doesn't work with the latest version of bourbon. Should I not be upgrading bourbon in this repo? And only ever stick with the version that specified in the sassquatch2 version package.json? 

cc @akdetrick

**Comment by akdetrick** [comment]
Use sassquatch `2.4.4`, which has no peer dependencies (and will install the correct version of bourbon)
