### ISSUE TITLE
Repo needs better file organization

### ISSUE THREAD

**Issue by sadafie** [meetup/meetup-web-components#25]
In `mup-web` we decided to have the test files live alongside the source files. I'm wondering if we want something different for this repo, i.e., a separate test directory: `src/tests/`, and possibly a separate story directory, `src/stories/`? As we're actively adding more components, the organization might help avoid a large, monolithic `src/` directory. I'm curious what folks who are actively working in this repo think. cc @mperrotti @akdetrick

**Comment by mmcgahan** [comment]
i have no objection.

**Comment by eilinora** [comment]
I'm a fan of keeping them side-by-side. I also like the consistency with the other repo's. It does make for a big /src folder but thing's feel pretty easy to find.

**Comment by sadafie** [comment]
I'm reopening this issue because it came up in yesterday's weekly web platform meeting as an agenda item.

@mmcgahan said that we should organize this repo sooner rather than later, and I think I tend to agree. 

Let's discuss and figure out if there's some way of organizing this that makes sense, even if it's something as simple as a separate `src/tests/` directory, and all components and stories staying root level together.

Also, related but maybe a separate issue, I noticed that `GroupCard` lives in this repo, while `EventCard` lives in `mup-web`. I remember we decided awhile back that composite components should live in `mup-web` whereas the base-level components live in this repo. Regardless of what we decide, I think it's strange that `EventCard` and `GroupCard` are in two different repos, so maybe we can address the moving of some of components in this issue as well.

'cc all stake-holders -- @eilinora @akdetrick @mperrotti @mattkime @willh-meetup

**Comment by eilinora** [comment]
EventCard and GroupCard i believe are super old and will be remade by enga team during mug home and event home  (we are doing group card soon)

I'm curious to know the motivation for moving the tests to another directory? Is it simply organizational?

**Comment by sadafie** [comment]
Yeah, a few people have mentioned that the top level source directory is to big/flat. I'v noticed other libraries maintain a separate tests directory, but I'm open to any suggestions. 

For GroupCard and EventCard - those will then both live in `mup-web` yes? I noticed that @jmhammons is/was doing some work on GroupCard in this repo recently?

**Comment by eilinora** [comment]
Oh didn't realize, @jmhammons we should coordinate on GroupCard if you guys are using this as well. @nlaz had started one as well in mup-web.

In terms of tests being in another directory, why keep stories in the main then and not put that in a subdirectory too?

I'm still a fan of the flat structure even though it is a lot of files, but :woman_shrugging:

**Comment by mmcgahan** [comment]
I think we could make a few directories, e.g. `layout` (bounds, chunk, section, etc...), `content` (avatar, date, rsvp, etc...), `controls` (button, toggle, tabs, checkbox, etc...), which would provide some conceptual organization as well as reduce the 'big flat directory' issue. It would make things slightly less browsable, but I *think* that the plan is to make our storybook setup the primary browsing mode, not the repo directory structure.

**Comment by eilinora** [comment]
definitely +1 @mmcgahan idea!

I'm still a fan of keeping corresponding files together, this feels like a nice way of creating logical groupings. It would give more incentive to keeping the storybook docs updated.

**Comment by akdetrick** [comment]
+1 on directories based on component purpose. This makes for more descriptive imports in client apps as well:

```es6
import Stripe from '~meetup-web-components/src/layout/Stripe';
import Bounds from '~meetup-web-components/src/layout/Bounds';
import Section from '~meetup-web-components/src/layout/Section';
import Chunk from '~meetup-web-components/src/layout/Chunk';

import { Tabs, TabsTab } from '~meetup-web-components/src/ui-components/Tabs';
import Button from '~meetup-web-components/src/ui-components/Button';
```

This could also pave the way for sensible indexing in each `src/[type]` dir:

```
import {
     Stripe,
     Bounds,
     Section,
     SectionTitle,
     Chunk
} from '~meetup-web-components/src/layout';
```

**Comment by mmcgahan** [comment]
I'd avoid `ui-components`, because everything in meetup-web-components is a React UI component. `media` would be okay - I had originally been thinking `content` but that's probably just as ambiguous.

IMO _navigation_ is a subset of _layout_, so I'd just put them all there.

**Comment by sadafie** [comment]
If it's alright with everyone here, I'm going to file a ticket to get this done in an upcoming sprint soon.

**Comment by akdetrick** [comment]
how about...
- layout (chunk, bounds, section, stripe)
- forms (text field, etc)
- media (icon, avatar)
- interactive (tabs, popover, modal)

**Comment by mmcgahan** [comment]
i like it. symlink `TogglePill` to `forms/`? 😉
