### ISSUE TITLE
How to save or print a meetup page?

### ISSUE THREAD

**Issue by haimivan** [meetup/meetup-web-components#731]
Hi,

I hope I address my question at the right place?

I would like to print or save the contents of a meetup event, e.g.: https://www.meetup.com/London-Data-Science-Journal-Club/events/262019020

Presently printing with chrome or firefox results in a pdf where all the details and comments are missing.

Saving it as a html page apparently saves the details and comments, but accessing the html page later without an internet connection does not show anything in the browser.

What can I do to perform my task?

Thanks in advance.

**Comment by haimivan** [comment]
Hi @hsbacot ,

thanks for your reaction to close my question.

Could you please tell me how I could solve my question / respectively: why did you close it?

Thanks in advance.

**Comment by mmcgahan** [comment]
Hi @haimivan. Thanks for your question! This repo is just for building out some UI components and is unrelated to printing web views. The best place to get support for questions like this is to email support@meetup.com - they will be able to triage the issue and make sure it gets routed to the right development team at Meetup that works on the event page.
